NUM_COPS = 8 # TO CHANGE
TIMEOUT = 50

GRID_SIZE = 13


#Robber
VISION_RADIUS = 2 # TO CHANGE
BANK_REWARD = 100
CAUGHT_PUNISHMENT = -70
TIMEOUT_PENALTY = 200
MOVE_FURTHER = 10
MOVE_CLOSER = 5